### ISSUE TITLE
Training more Chinese speaking person error: ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by Bohemian-self** [FENRlR/MB-iSTFT-VITS2#12] opened 2023-11-08 11:34 UTC
**Traceback (most recent call last):
  File "/content/MB-iSTFT-VITS2/train_ms.py", line 492, in <module>
    main()
  File "/content/MB-iSTFT-VITS2/train_ms.py", line 57, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "/root/.local/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/.local/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/root/.local/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/content/MB-iSTFT-VITS2/train_ms.py", line 86, in run
    train_dataset = TextAudioSpeakerLoader(hps.data.training_files, hps.data)
  File "/content/MB-iSTFT-VITS2/data_utils.py", line 202, in __init__
    self._filter()
  File "/content/MB-iSTFT-VITS2/data_utils.py", line 214, in _filter
    for audiopath, sid, text in self.audiopaths_sid_text:
ValueError: too many values to unpack (expected 3)**

I set print(self.audiopaths_sid_text) to try to analyze the problem, and the result is as follows:
[['./Auwa/Auwa_AllAge_00055.wav', 'Auwa_All', 'ㄏㄠˇㄉㄞˇ ㄧㄝˇ ㄕˋ ㄅㄢˋ ㄌㄜ˙ ㄋㄧㄢˊ ㄎㄚˇㄐㄧˋ ㄎㄚˇ ㄉㄜ˙ ㄖㄣˊ， ㄧㄠˋㄕˋ ㄅㄨˋ ㄌㄞˊ， ㄋㄚˋ ㄎㄜˇ ㄌㄤˋㄈㄟˋ ㄌㄜ˙。'], ['./Auwa_18R/Auwa_AdultOnly_00012.wav', 'Auwa_18R', 'ㄏㄚˉ ㄚ˙ㄏㄚˉ ㄚ˙， ㄜˋ ㄅㄨˊㄧㄠˋ~ ㄅㄨˋㄒㄧㄥˊ ㄏㄚˉ ㄣˊ~ ㄋㄧˇ ㄅㄚˇㄕㄡˇ ㄕㄡˇㄓˇ ㄔㄡˉㄔㄨˉㄌㄞˊ。'],……]]
And then the same content keeps getting output for about a few dozen lines
How should I change data_utils.py to eliminate errors? Or how to find the fault? (I train on Google Colab)

**Comment by FENRlR** [comment] 2023-11-09 01:22
``` 
File "/content/MB-iSTFT-VITS2/data_utils.py", line 214, in _filter
for audiopath, sid, text in self.audiopaths_sid_text:
ValueError: too many values to unpack (expected 3)* 
```
This error means that there was an element that contains more than 3 values from [`self.audiopaths_sid_text`](https://github.com/FENRlR/MB-iSTFT-VITS2/blob/main/data_utils.py#L181). Since each element of `self.audiopaths_sid_text` originates from a [split](https://github.com/FENRlR/MB-iSTFT-VITS2/blob/main/utils.py#L138), you may consider a line in the text file which contains "|" more than twice.

To find that problematic line, you can try something like this in [data_utils.py](https://github.com/FENRlR/MB-iSTFT-VITS2/blob/main/data_utils.py#L214) :

```
sus=0 #- !
for audiopath, sid, text in self.audiopaths_sid_text: 
    sus+=1 #- !
    print(sus) #- !

    if self.min_text_len <= len(text) and len(text) <= self.max_text_len:
        audiopaths_sid_text_new.append([audiopath, sid, text])
        lengths.append(os.path.getsize(audiopath) // (2 * self.hop_length))

    self.audiopaths_sid_text = audiopaths_sid_text_new
    self.lengths = lengths
```

(Duplicate of #9)

**Comment by Bohemian-self** [comment] 2023-11-09 14:05
Whether can be understood as “wavfile_path|speaker_id|transcript” speaker_id can only be int type (0) rather than the str (Auwa_All)?

**Comment by Bohemian-self** [comment] 2023-11-09 14:45
Ok,I know.Thanks very much!

**Closed** 2023-11-09 14:45 UTC
